### ISSUE TITLE
Some problems with deploy bot

### ISSUE THREAD

**Issue by R-Morpheus** [daniellwdb/rok-title-keeper#22]
Your project seemed very interesting to me, I decided to try it, but I experienced some difficulties. I went through all the configuration steps, I also installed `opencv v 4.6`, changed the `PORT` value in `index.ts` on your own. Specified the main `PATH` for `platform-tools`. But when I run `npx tsx .` for some reason nothing happens, there are no errors either. 

But as I understand it, the connection with BlueStacks is correct, perhaps the problem is in the very connection of the bot in the discord.

Have you encountered this problem during development? Maybe you have thoughts on how to fix it? Thank you in advance!![image.png](https://github.com/daniellwdb/rok-title-keeper/assets/107617521/e474cb68-f05d-4fec-9bc4-5cbde785a5aa)

**Comment by R-Morpheus** [comment]
I managed to launch the bot, it works fine, but the problem is still with BlueStacks. For some reason, every time the title is requested, the bot responds that the `device is offline`. 
Perhaps the problem is that the emulator has different `ports (5557,5558)`. 
At this moment I do not understand how to fix the error. 
I also used the commands `adb`: 
```
adb kill-server 
adb start-server
adb connect localhost:555... 
```
but all in vain. 

I hope you will help me!

**Comment by daniellwdb** [comment]
Hi, you shouldn't be changing anything in the source files if you didn't make specify anything other than the defaults for adb. Make sure to configure BlueStacks to expose a adb port and the script will dynamically get the port from BlueStack's configuration file

**Comment by knorres** [comment]
I had the same issue and tried for days. Somewhen I restarted the server and bluestacks instance changed to port 5555 at Android, before there were many different ports but since that it’s working pretty good. Am 24.07.2023 um 09:09 schrieb Daniell ***@***.***>:﻿
Hi, you shouldn't be changing anything in the source files if you didn't make specify anything other than the defaults for adb. Make sure to configure BlueStacks to expose a adb port and the script will dynamically get the port from BlueStack's configuration file

**Comment by daniellwdb** [comment]
Feel free to open another issue with your attempt to fix it if it's still not working
